### ISSUE TITLE
运行Latency.py，提示缺失../Assets/sine_file_dict_16_10.dict文件

### ISSUE THREAD

**Issue by shazi4399** [xingpz2008/TriFSS#2]
嗨，我在测试`Benchmark/Latency.py`文件

我测试步骤如下：
step1：开两个命令行端口

step2：在窗口1中，我执行了如下命令
```bash
(base) zhanghao@thinkcentre:~/Downloads/mycode/TriFSS/Benchmark$ python Latency.py -r 0
```

step3:在窗口2中，我执行了如下命令
```bash
(base) zhanghao@thinkcentre:~/Downloads/mycode/TriFSS/Benchmark$ python Latency.py -r 1
```

发现报错，完整报错信息如下：
```bash
Process Process-2:
Traceback (most recent call last):
  File "/home/zhanghao/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zhanghao/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhanghao/Downloads/mycode/TriFSS/Benchmark/Latency.py", line 27, in run_test
    function(x=GroupElements(i), party=party)
  File "/home/zhanghao/anaconda3/lib/python3.9/site-packages/Pythonic_TriFSS/Math/sine.py", line 108, in sin
    file_dict: dict = party.local_recv(f'sine_file_dict_{x.bitlen}_{x.scalefactor}.dict')
  File "/home/zhanghao/anaconda3/lib/python3.9/site-packages/Pythonic_TriFSS/Communication/semi_honest_party.py", line 33, in local_recv
    data = api.local_recv(filename)
  File "/home/zhanghao/anaconda3/lib/python3.9/site-packages/Pythonic_TriFSS/Communication/api.py", line 119, in local_recv
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../Assets/sine_file_dict_16_10.dict'
Process Process-1:
Traceback (most recent call last):
  File "/home/zhanghao/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zhanghao/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhanghao/Downloads/mycode/TriFSS/Benchmark/Latency.py", line 27, in run_test
    function(x=GroupElements(i), party=party)
  File "/home/zhanghao/anaconda3/lib/python3.9/site-packages/Pythonic_TriFSS/Math/sine.py", line 108, in sin
    file_dict: dict = party.local_recv(f'sine_file_dict_{x.bitlen}_{x.scalefactor}.dict')
  File "/home/zhanghao/anaconda3/lib/python3.9/site-packages/Pythonic_TriFSS/Communication/semi_honest_party.py", line 33, in local_recv
    data = api.local_recv(filename)
  File "/home/zhanghao/anaconda3/lib/python3.9/site-packages/Pythonic_TriFSS/Communication/api.py", line 119, in local_recv
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../Assets/sine_file_dict_16_10.dict'
Benchmarking Result: 0.9630019664764404s in 1000 operations
```

提示缺少`../Assets/sine_file_dict_16_10.dict`文件，请问应该怎样生成这个文件？

**Comment by xingpz2008** [comment]
该脚本文件只包含了协议的在线部分，因此在执行前需要执行协议离线部分生成数据，方法可以参考[Debug/debug_sin_A.py](https://github.com/xingpz2008/TriFSS/blob/main/Debug/debug_Sin_A.py#L8-L9)，关于协议的其他细节，可以关注今年ICC发表的文章TriFSS: Secure Trigonometric Function Evaluation via Function Secret Sharing

**Comment by shazi4399** [comment]
哇OK，这个问题我也解决了。非常感谢您的指导。
